### ISSUE TITLE
如何使用http/socks代理的情况下使用这个脚本？谢谢

### ISSUE THREAD

**Issue by v2less** [yufeikang/ai-cli#1]
虽然已经设置了终端中的环境变量(oh-my-zsh,proxy工具)，但是并不有效。
```bash
Assistant:
Asking...WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f17728a3b80>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /v1/chat/completions
Asking...WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f17728a3d60>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /v1/chat/completions
```

**Comment by yufeikang** [comment]
已经支持代理。请帮忙测试一下。谢谢

**Comment by v2less** [comment]
- 代理里的变量是 `ALL_PROXY2`,改成`ALL_PROXY`。
- 改完之后，一直卡在`Asking`

**Comment by yufeikang** [comment]
不好意思。我已经修复变量的typo。你现在可以使用
`export ALL_PROXY=socks5://x.x.x.:1080`
你可以通过--debug参数看其他lib里的日志来判断原因

不过建议你使用 OPENAI_API_BASE 环境变量。这种一种正想代理的思路应该更稳定。readme里面提供了一个链接，介绍了如何用cloudflare worker来搭建正向代理的方法。

你可以先试试我自己的server测试一下： `export OPENAI_API_BASE=https://ai.kangyufei.net/v1`

**Comment by v2less** [comment]
```bash
python ai.py --debug ask "python学习路线图"
DEBUG:cli:debug mode enabled
DEBUG:cli:using socks proxy: socks5://127.0.0.1:1081
DEBUG:cli:args: Namespace(api_key=None, no_stream=False, raw=False, model='gpt-3.5-turbo', log_level='INFO', debug=True, endpoint=None, proxy=None, command='ask', question=['python学习路线图'])
DEBUG:cli:command: ask
Asking...DEBUG:cli:asking question: python学习路线图
Asking...WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)'))': /v1/chat/completions
Asking...WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)'))': /v1/chat/completions
Asking...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sandy/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sandy/Downloads/python/ai.py", line 329, in <module>
    main()
  File "/home/sandy/Downloads/python/ai.py", line 321, in main
    CMD[command]()
  File "/home/sandy/Downloads/python/ai.py", line 306, in ask_cmd
    ask(args.question, stream=stream)
  File "/home/sandy/Downloads/python/ai.py", line 223, in ask
    response = _ask(question, stream=stream)
  File "/home/sandy/Downloads/python/ai.py", line 211, in _ask
    return openai.ChatCompletion.create(
  File "/home/sandy/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/sandy/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/sandy/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 216, in request
    result = self.request_raw(
  File "/home/sandy/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: SOCKSHTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))

```
当使用了OPENAI_API_BASE 环境变量，是可以的。

不过，我用另外一个项目，使用http/socks代理是可以使用的。
<https://github.com/j178/chatgpt>
