### ISSUE TITLE
Error when execute ai commands

### ISSUE THREAD

**Issue by taiqn** [yufeikang/ai-cli#14]
_Traceback (most recent call last):
  File "/Users/tai/Library/Python/3.9/bin/ai", line 5, in <module>
    from ai_cli.cli import cli
  File "/Users/tai/Library/Python/3.9/lib/python/site-packages/ai_cli/cli.py", line 10, in <module>
    from ai_cli.bot import Bot, get_bot
  File "/Users/tai/Library/Python/3.9/lib/python/site-packages/ai_cli/bot/__init__.py", line 12, in <module>
    from EdgeGPT import Chatbot, ConversationStyle
  File "/Users/tai/Library/Python/3.9/lib/python/site-packages/EdgeGPT.py", line 953, in <module>
    class Query:
  File "/Users/tai/Library/Python/3.9/lib/python/site-packages/EdgeGPT.py", line 962, in Query
    Cookie.import_data()
  File "/Users/tai/Library/Python/3.9/lib/python/site-packages/EdgeGPT.py", line 934, in import_data
    cls.current_filepath = cls.files()[cls.current_file_index]
IndexError: list index out of range_

Hi, I encouter this error when running **ai setting -e** or other ai-commands. Hope you could help

Thanks
Tai

**Comment by taiqn** [comment]
I'm now not  able to set the path for bing_cookie

**Comment by yufeikang** [comment]
try this:
`pip3 install -U EdgeGPT`
