### ISSUE TITLE
ValueError: Unknown level: '<ai_cli.setting.SettingField object at 0x7f329f91d4f0>'

### ISSUE THREAD

**Issue by fieri** [yufeikang/ai-cli#17]
Traceback (most recent call last):
  File "/home/focus/.local/bin/ai", line 5, in <module>
    from ai_cli.cli import cli
  File "/home/focus/.local/lib/python3.9/site-packages/ai_cli/cli.py", line 214, in <module>
    init_logging(setting.log_level.get_value() if not args.debug else "DEBUG")
  File "/home/focus/.local/lib/python3.9/site-packages/ai_cli/__init__.py", line 20, in init_logging
    logging.getLogger("ai_cli").setLevel(level=log_level)
  File "/usr/local/python3/lib/python3.9/logging/__init__.py", line 1409, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/python3/lib/python3.9/logging/__init__.py", line 194, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: '<ai_cli.setting.SettingField object at 0x7f329f91d4f0>'

**Comment by fieri** [comment]
Traceback (most recent call last):
  File "/home/focus/.local/bin/ai", line 5, in <module>
    from ai_cli.cli import cli
  File "/home/focus/.local/lib/python3.11/site-packages/ai_cli/cli.py", line 10, in <module>
    from ai_cli.bot import Bot, get_bot
  File "/home/focus/.local/lib/python3.11/site-packages/ai_cli/bot/__init__.py", line 12, in <module>
    from ai_cli.setting import Setting
  File "/home/focus/.local/lib/python3.11/site-packages/ai_cli/setting.py", line 108, in <module>
    setting = read_setting()
              ^^^^^^^^^^^^^^
  File "/home/focus/.local/lib/python3.11/site-packages/ai_cli/setting.py", line 97, in read_setting
    return Setting.from_dict(json.load(f))
                             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 14 (char 15)
