### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 2 column 14 (char 15)

### ISSUE THREAD

**Issue by fieri** [yufeikang/ai-cli#18]
Traceback (most recent call last):
  File "/home/focus/.local/bin/ai", line 5, in <module>
    from ai_cli.cli import cli
  File "/home/focus/.local/lib/python3.11/site-packages/ai_cli/cli.py", line 10, in <module>
    from ai_cli.bot import Bot, get_bot
  File "/home/focus/.local/lib/python3.11/site-packages/ai_cli/bot/__init__.py", line 12, in <module>
    from ai_cli.setting import Setting
  File "/home/focus/.local/lib/python3.11/site-packages/ai_cli/setting.py", line 108, in <module>
    setting = read_setting()
              ^^^^^^^^^^^^^^
  File "/home/focus/.local/lib/python3.11/site-packages/ai_cli/setting.py", line 97, in read_setting
    return Setting.from_dict(json.load(f))
                             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 14 (char 15)

**Comment by yufeikang** [comment]
``` rm .config/ai_cli/setting.json```

and retry

**Comment by yufeikang** [comment]
Hello. I found the reason for this error during debugging today. Please try deleting the configuration file with the command below and try again.

`rm .config/ai_cli/setting.json`
